### ISSUE TITLE
Need help in understanding the DispatcherProvider.kt

### ISSUE THREAD

**Issue by sagarpatel288** [BirjuVachhani/login-mvvm-final-code#1]
So… I was trying to understand coroutines…
I found your example… but I need your help to understand something…
You have used dispatcher in such a way that I could not understand…
```
interface DispatcherProvider {
// comment by srdpatel: 12/3/2019 single expression function, expression body
fun main(): CoroutineDispatcher = Dispatchers.Main
fun default(): CoroutineDispatcher = Dispatchers.Default
fun io(): CoroutineDispatcher = Dispatchers.IO
fun unconfined(): CoroutineDispatcher = Dispatchers.Unconfined
}

class DefaultDispatcherProvider : DispatcherProvider
```
And then in viewModel:

```
class LoginActivityViewModel(private val dispatchers: DispatcherProvider = DefaultDispatcherProvider()) : ViewModel()
```

And then inside ```LoginActivityViewModel``:

```
fun login(email: String, password: String) = viewModelScope.launch(dispatchers.default()) {
- -
}
```
I want to understand why did you not use dispatcher simply like below:

```
fun login(email: String, password: String) = viewModelScope.launch(Dispatchers.Default) {
- -
}
```

**Comment by BirjuVachhani** [comment]
In your version, you hard-coded the Dispatcher so now when you want to test your in an environment where that dispatcher might not be available, you won't be able to do it.

Example: suppose you have used `Dispatchers.Main` somewhere in your repository or ViewModel and now you want to unit test your code on the JVM. As Dispatchers.Main is Android's MainThread, it won't be available on the JVM. Hence your test will fail.

The way I used it helps me to provide different configuration while testing the code and also I don't have to make changes to each every place I used Dispatchers
